### ISSUE TITLE
Synk duplicate yml file and boiler plate code

### ISSUE THREAD

**Issue by L00163597** [ruthlennonatu/bsc23grassroots#147]
@PratikShelke-1 I was examining both of your Snyk yml file to try and understand them, but they are both doing the exact same thing, so why do we need 2? 

Also, it seems like they are doing nothing with the docker image it is supposed to be building is the boiler plate code provided by the Actions workshop. The only thing you seem to have added is the token, which again is not doing anything, as the Synk GitHub integration is the only thing that is actually doing any work. This is fine, but the files are irrelevant.  

So fix the files or remove both. If you can't explain why and we can try to work on it to fix it

**Comment by PratikShelke-1** [comment]
Both files are fixed. Need to add secrets.
Files are working on my personal repo

**Comment by L00163597** [comment]
@PratikShelke-1 are you providing a demo on what these yml files are going to do? Also, just for cleanliness I'm going to remove them from Dev branch as I know you have them updated on your automated pipeline branch
