### ISSUE TITLE
Move "test_django.py" into unitTests folder

### ISSUE THREAD

**Issue by farankhanatu** [ruthlennonatu/bsc23grassroots#153]
In the Develop branch, there is a unit test file named "test_django.py" in **Source/grassroots** directory. 

Please move this unit test into the **Source/grassroots/tests/unitTests** directory so that GitHub Action file can run the test.

**Comment by PratikShelke-1** [comment]
I haven't created this file.

**Comment by farankhanatu** [comment]
It seems that this file contains the same code present in the unitTests folder. I am creating a branch from Develop and will simply remove this file and will create a Pull Request to Develop.

**Comment by L00163597** [comment]
The file is no longer B)
