### ISSUE TITLE
Pipeline Automation using docker and AWS

### ISSUE THREAD

**Issue by L00160463** [ruthlennonatu/bsc23grassroots#73]
Pipeline Automation Issue: Making sure that the system's building, testing, and deploying processes are automated and run smoothly. It involves picking the right tools, setting up a process where changes are automatically tested and deployed, and making sure the system is easy to maintain.

**Comment by PratikShelke-1** [comment]
An automated pipeline is done by using a docker image and that image will get deployed on the AWS EC2 server.

**Comment by PratikShelke-1** [comment]
Working on the demo
